// <auto-generated />
using IS405.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IS405.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20221027201444_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("IS405.Models.Employee", b =>
                {
                    b.Property<int>("byuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("byuName")
                        .HasColumnType("TEXT");

                    b.Property<string>("classCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("emplRecord")
                        .HasColumnType("TEXT");

                    b.Property<string>("expectedWorkHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("hireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("increaseInputDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("international")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastPayIncrease")
                        .HasColumnType("TEXT");

                    b.Property<string>("majorYear")
                        .HasColumnType("TEXT");

                    b.Property<bool>("nameChangeCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("payGradTuition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("payIncreaseAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("payRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("positionType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("qualtricsSurveySent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("semester")
                        .HasColumnType("TEXT");

                    b.Property<bool>("submittedForm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("supervisor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("terminated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("terminationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("workAuthorizationEmailSent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("workAuthorizationReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("byuID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            byuID = 9988,
                            byuName = "Mickey Mouse",
                            classCode = "IS-201",
                            email = "mmouse@gmail.com",
                            expectedWorkHours = "8-5",
                            firstName = "Mickey",
                            gender = "Male",
                            hireDate = "08-10-2022",
                            international = false,
                            lastName = "Mouse",
                            nameChangeCompleted = false,
                            payGradTuition = false,
                            phone = "801-123-4567",
                            positionType = "TA",
                            qualtricsSurveySent = false,
                            semester = "Winter",
                            submittedForm = false,
                            supervisor = "Hilton",
                            terminated = false,
                            workAuthorizationReceived = false,
                            year = 2023
                        },
                        new
                        {
                            byuID = 891617523,
                            byuName = "Walter White",
                            classCode = "IS-413",
                            email = "heisenberg@gmail.com",
                            expectedWorkHours = "8-5",
                            firstName = "Walter",
                            gender = "Male",
                            hireDate = "05-17-2021",
                            international = false,
                            lastName = "White",
                            nameChangeCompleted = false,
                            payGradTuition = false,
                            phone = "425-555-7711",
                            positionType = "TA",
                            qualtricsSurveySent = false,
                            semester = "Fall",
                            submittedForm = false,
                            supervisor = "Hilton",
                            terminated = true,
                            terminationDate = "12-17-2021",
                            workAuthorizationReceived = false,
                            year = 2021
                        },
                        new
                        {
                            byuID = 452331110,
                            byuName = "Elenor Shellstrop",
                            classCode = "IS-115",
                            email = "badplace@gmail.com",
                            expectedWorkHours = "12-4",
                            firstName = "Elenor",
                            gender = "Female",
                            hireDate = "01-10-2020",
                            increaseInputDate = "04-29-2020",
                            international = false,
                            lastName = "Shellstrop",
                            lastPayIncrease = "05-01-2020",
                            nameChangeCompleted = false,
                            payGradTuition = false,
                            payIncreaseAmount = "$0.67",
                            phone = "413-887-9145",
                            positionType = "TA",
                            qualtricsSurveySent = false,
                            semester = "Spring",
                            submittedForm = false,
                            supervisor = "Burton",
                            terminated = false,
                            workAuthorizationReceived = false,
                            year = 2020
                        },
                        new
                        {
                            byuID = 223558870,
                            byuName = "Elena Gilbert",
                            classCode = "IS-403",
                            email = "vampiresrules@gmail.com",
                            expectedWorkHours = "7-11",
                            firstName = "Elena",
                            gender = "Female",
                            hireDate = "07-31-2021",
                            international = false,
                            lastName = "Gilbert",
                            nameChangeCompleted = false,
                            payGradTuition = false,
                            phone = "685-773-6592",
                            positionType = "RA",
                            qualtricsSurveySent = false,
                            semester = "Fall",
                            submittedForm = false,
                            supervisor = "Anderson",
                            terminated = false,
                            workAuthorizationReceived = false,
                            year = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
