// <auto-generated />
using IS405.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IS405.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("IS405.Models.Employee", b =>
                {
                    b.Property<string>("byuID")
                        .HasColumnType("TEXT");

                    b.Property<string>("byuName")
                        .HasColumnType("TEXT");

                    b.Property<string>("classCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("emplRecord")
                        .HasColumnType("TEXT");

                    b.Property<string>("expectedWorkHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("hireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("increaseInputDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("international")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastPayIncrease")
                        .HasColumnType("TEXT");

                    b.Property<string>("majorYear")
                        .HasColumnType("TEXT");

                    b.Property<bool>("nameChangeCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("payGradTuition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("payIncreaseAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("payRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("positionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("qualtricsSurveySent")
                        .HasColumnType("TEXT");

                    b.Property<string>("semester")
                        .HasColumnType("TEXT");

                    b.Property<string>("submittedForm")
                        .HasColumnType("TEXT");

                    b.Property<string>("supervisor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("terminated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("terminationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("workAuthorizationEmailSent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("workAuthorizationReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("byuID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            byuID = "11-222-1234",
                            byuName = "Mickey Mouse",
                            classCode = "IS-201",
                            email = "mmouse@gmail.com",
                            expectedWorkHours = "8-5",
                            firstName = "Mickey",
                            gender = "Male",
                            hireDate = "08-12-2022",
                            international = false,
                            lastName = "Mouse",
                            nameChangeCompleted = false,
                            payGradTuition = false,
                            phone = "801-123-4567",
                            positionType = "TA",
                            semester = "Winter",
                            supervisor = "Hilton",
                            terminated = false,
                            workAuthorizationReceived = false,
                            year = 2023
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
